//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyThirdProject2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyThirdDatabase2ModelContainer : DbContext
    {
        public MyThirdDatabase2ModelContainer()
            : base("name=MyThirdDatabase2ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Platform> Platforms { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Score> Scores { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<User_Information> User_Information { get; set; }
    }
}
